<a href="https://colab.research.google.com/github/jackie-Gung/BigData_Study/blob/main/Chap_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. 파이썬 프로그램 기본

## 제어문
## 1) if 문
## 2) for 문
## 3) while 문

In [ ]:
## if 문

age = int(input("What is your age: "))
if age < 18 :
    print("You cannot drive")
else :
    print("You can drive")

What is your age: 22
You can drive


In [ ]:
## if 문

num = int(input("입력하는 숫자가 6~20 사이 짝수인가? "))
if num >= 6 and num <= 20 :
    if num % 2 == 0 :
        print("Yes")
    else :
        print("No")
else :
    print("No")

입력하는 숫자가 6~20 사이 짝수인가? 18
Yes


In [ ]:
## for 문

numbers = [1,2,3,4,5,6,7]
sum = 0
for n in numbers :
    sum += n
print(sum)

28


In [ ]:
### 여러 list를 한번에 불러올 때 : enumerate & zip

names = ["Jackie", "Amy", "Clare", "Danny"]
ages = [22, 29, 57, 56]

for i, (name, age) in enumerate(zip(names,ages)) :
    print(i, name, age)

0 Jackie 22
1 Amy 29
2 Clare 57
3 Danny 56


In [ ]:
## while 문

num = int(input("Enter a number : "))
i = 1
sum = 0
while (i <= num) :
    sum += i
    i += 1
print(sum)

Enter a number : 15
120


In [ ]:
## while문에서 done : if & try & except

num = 0
tot = 0.0

while True :
    sval = input("Enter a number : ")
    if sval == "done" :
        break
    try :
        fval = float(sval)
    except :
        print("Invalid input")
        continue
    num += 1
    tot += fval
print(tot, num , tot/num)

Enter a number : 24
Enter a number : 56
Enter a number : done
80.0 2 40.0


In [ ]:
astr = "124"
try :
    print("Hello")
    islnt = int(astr)
    print("World")
except :
    islnt = "Integer로 변환할 수 없습니다."
print("Done", islnt)

Hello
World
Done 124


In [ ]:
## 2. Package
### 1. numpy, pandas : numpy는 배열 데이터를, pandas는 데이터프레임 데이터 관리하는 패키지 -> 통계분석에 필수적인 패키지
### 2. SKlearn, Tensorflow : 머신러닝을 위한 패키지 / SKlearn은 classification, regression, clustering, sufficient dimension 모델링 지원
###                          Tensorflow는 구글에서 제공하는 머신러닝 및 딥러닝 개발을 위한 패키지
### 3. matplotlilb ,seaborn : 

In [ ]:
## 3. 자료구조 

In [ ]:
## list 

### list 생성 
sample_list1 = [1,2,3,4,5]
print(sample_list1)

### Indexing & Slicing 
print(sample_list1[0])
print(sample_list1[:-3])
print(sample_list1[0:3:2])
print(sample_list1[1::-1])
print(sample_list1[3::-1])
print(sample_list1[-3::-1])

[1, 2, 3, 4, 5]
1
[1, 2]
[1, 3]
[2, 1]
[4, 3, 2, 1]
[3, 2, 1]


In [ ]:
### list 연산 : +, *

sample_list1 = [1,2,3,4,5]
print(len(sample_list1))

list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)
print(list1*2)

5
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [ ]:
### list method : append, insert, remove, pop, extend, copy, reverse, sort, count, index, clear

list = [1,2,3,4,5]
list2 = [6,7,8,9,10]

list.append(9)
print(list)

list.insert(6,10)
print(list)

list.remove(10)
print(list)

list.pop()
print(list)

list.extend(list2)
print(list)

list3 = list.copy()
print(list3)

list.reverse()
print(list)

list.sort()
print(f' sort : {list}')

list3.count(1)
print(f'count : {list3}')

print(list3.index(3))

list3.clear()
print(list3)

[1, 2, 3, 4, 5, 9]
[1, 2, 3, 4, 5, 9, 10]
[1, 2, 3, 4, 5, 9]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
 sort : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
count : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
2
[]


In [ ]:
## array
## array는 numpy에서 작성된 class이므로 np.array로 써야 한다

import numpy as np

### 1차원 배열
array = np.array([1,2,3,4,5])
print(array) # list와 다르게 ','가 뜨지 않는다

### 2차원 배열
array2 = np.array([
    [1,2,3,4,5], 
    [6,7,8,9,10]])
print(array2)

### type difference between list & array
print(type(list)) # list type
print(type(array2)) # array type

### index & slicing
print(array[0:2])
print(array2[0][1])
print(array2[0:])
print(array2[:, 1:3]) # (row, column) enter

# array data type
print(array2.dtype)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'list'>
<class 'numpy.ndarray'>
[1 2]
2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 3]
 [7 8]]
int32


In [ ]:
## array 속성

print(array2 * array2)
print(array2 - array2)
print(1/array2)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1       ]]


In [ ]:
## DataFrame
## pandas에 있는 class쓰는 것이므로 pd.DataFrame으로 써야 한다.

### 1. 생성 
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(df)

### 2. dictionary 이용
heros = {
    'age' : [20,24,48],
    'height' : [183,192,175],
    'weight' : [77,83,65],
    'gender' : ["M", "M","F"]
}
name = ["Superman", "Spiderman", "Betman"]
df2 = pd.DataFrame(heros, index = name)
print(df2)
df2 # 표처럼 출력됨

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
           age  height  weight gender
Superman    20     183      77      M
Spiderman   24     192      83      M
Betman      48     175      65      F


age  height  weight gender
Superman    20     183      77      M
Spiderman   24     192      83      M
Betman      48     175      65      F

In [ ]:
### 난수를 이용한 dataframe : random.seed / random.randint

import numpy as np
import pandas as pd

np.random.seed(2) # 매번 돌려도 같은 값이 나오게 함. seed() 설정 안하면 돌릴때마다 다른 값 나옴
df = pd.DataFrame(np.random.randint(1,10,(3,3)))
df

0  1  2
0  9  9  7
1  3  9  8
2  3  2  6

In [ ]:
np.random.seed(2022)
df = pd.DataFrame(np.random.randint(10,22,(4,5)),
                 index = ['a','b','c','d'],
                 columns = ['A','B','C','D','E'])
df

A   B   C   D   E
a  13  20  20  19  14
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16

In [ ]:
print(df.head(4))
print(df.info())
print(df.shape)

    A   B   C   D   E
a  13  20  20  19  14
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int32
 1   B       4 non-null      int32
 2   C       4 non-null      int32
 3   D       4 non-null      int32
 4   E       4 non-null      int32
dtypes: int32(5)
memory usage: 112.0+ bytes
None
(4, 5)


In [ ]:
# df[] : []안에 column명만 가능. row명 쓰면 error
df['A']
df[['A','B']]

# df. : column 추출
print(df.A)
print(df[df['A']>15])
print(df[(df['A']>15) | (df['B'] < 16)])

a    13
b    21
c    16
d    21
Name: A, dtype: int32
    A   B   C   D   E
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16
    A   B   C   D   E
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16


In [ ]:
# df.query() : data 추출하는 함수

print(df.query('index == 0'))
print(df.query('C == 17'))
print(df.query('A == 21 | D == 20'))

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []
    A   B   C   D   E
b  21  16  17  12  10
    A   B   C   D   E
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16


In [ ]:
# df. drop() : 지정한 열을 제외한 데이터 추출
df.drop("A",axis=1) # axis에 1 외 다른 숫자 넣으면 error

B   C   D   E
a  20  20  19  14
b  16  17  12  10
c  18  15  20  20
d  13  10  16  16

In [ ]:
# df.loc[] : [행 index] or [row index, columb index]
# 대신에 loc[]은 index 값으로 string을 대입해야 하는듯

print(df.loc["a"])
print(df.loc["a":"c"])
print(df.loc[df.A>15])

# df.iloc[] : only integer available for row

print(df)
print(df.iloc[-1])

A    13
B    20
C    20
D    19
E    14
Name: a, dtype: int32
    A   B   C   D   E
a  13  20  20  19  14
b  21  16  17  12  10
c  16  18  15  20  20
    A   B   C   D   E
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16
    A   B   C   D   E
a  13  20  20  19  14
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16
A    21
B    13
C    10
D    16
E    16
Name: d, dtype: int32


In [ ]:
### data 속성 : info, headm tail, axes, index, columns, values, ndim, shape, size, dtypes, count

print(df.head())
print(df.tail())
print(df.axes)
print(df.index)
print(df.columns)
print(df.ndim)
print(df.values) # numpy형식으로 변환
print(df.shape) # (row,column)
print(df.count)

    A   B   C   D   E
a  13  20  20  19  14
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16
    A   B   C   D   E
a  13  20  20  19  14
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16
[Index(['a', 'b', 'c', 'd'], dtype='object'), Index(['A', 'B', 'C', 'D', 'E'], dtype='object')]
Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
2
[[13 20 20 19 14]
 [21 16 17 12 10]
 [16 18 15 20 20]
 [21 13 10 16 16]]
(4, 5)
<bound method DataFrame.count of     A   B   C   D   E
a  13  20  20  19  14
b  21  16  17  12  10
c  16  18  15  20  20
d  21  13  10  16  16>


In [ ]:
# 4. 파일을 읽어들이는 방법

In [2]:
## csv 파일 입력
### pd.read_csv('sample.csv')
### df.to_csv('sample3.csv')

In [5]:
## 인터넷 상의 csv 파일 입력
import pandas as pd
math = pd.read_csv("http://home.ewha.ac.kr/~josong/dm/mathcat.data", sep = '\s+')
print(math.head(n=4))
print(math.tail(n=4))

   hsgpa  hsengl hscalc    course passed outcome
1   78.0      80    Yes  Mainstrm     No  Failed
2   66.0      75    Yes  Mainstrm    Yes  Passed
3   80.2      70    Yes  Mainstrm    Yes  Passed
4   81.7      67    Yes  Mainstrm    Yes  Passed
     hsgpa  hsengl hscalc    course passed outcome
391   77.0      79    Yes  Mainstrm    Yes  Passed
392   80.7      70    Yes  Mainstrm    Yes  Passed
393   80.7      81    Yes  Mainstrm    Yes  Passed
394   82.2      86    Yes  Catch-up    Yes  Passed


In [6]:
pd.set_option("display.max.row", 20) # 앞뒤로 모두 20행만 보여줌
pd.set_option("display.max.column", None) # 모든 컬럼을 다 보여줌
math

hsgpa  hsengl hscalc    course passed outcome
1     78.0      80    Yes  Mainstrm     No  Failed
2     66.0      75    Yes  Mainstrm    Yes  Passed
3     80.2      70    Yes  Mainstrm    Yes  Passed
4     81.7      67    Yes  Mainstrm    Yes  Passed
5     86.8      80    Yes  Mainstrm    Yes  Passed
..     ...     ...    ...       ...    ...     ...
390   88.3      90    Yes  Mainstrm    Yes  Passed
391   77.0      79    Yes  Mainstrm    Yes  Passed
392   80.7      70    Yes  Mainstrm    Yes  Passed
393   80.7      81    Yes  Mainstrm    Yes  Passed
394   82.2      86    Yes  Catch-up    Yes  Passed

[394 rows x 6 columns]

In [7]:
# 5. 함수 만들기

In [8]:
## 피보나치 수열 출력 함수 예제 1

def fib(n) :
    a, b = 0, 1
    while a < n :
        print(a, end = ' ')
        a, b = b, a+b
fib(20)

0 1 1 2 3 5 8 13 

In [9]:
## 피보나치 수열 출력 함수 예제 1

def fib(n) :
    a, b = 0, 1
    while a < n :
        print(a, end = ' ')
        a, b = b, a+b
fib(20)

0 1 1 2 3 5 8 13 

In [10]:
## map() function : list or tuple (map(function, 매개변수))

int1 = [1,2,3,4]
int2 = [5,6,7,8]
list(map(lambda x,y : x+y, int1, int2))

[6, 8, 10, 12]

In [11]:
### 모듈 : 파이썬 정의를 파일에 넣고 스크립트나 인터프리터 대화형 모드에서 사용할 수 있는 파일

In [12]:
## 모듈 만들기

# 정규분포와 감마분포 pdf 그리는 모듈
# matplotlib.pyplot : 명령어 스타일로 동작하는 함수의 모음. 간편하게 그래프를 만들 수 있음

def normplt(m,s) :
    import numpy as np
    import matplotlib.pyplot as plt
    from scipy.stats import norm
    x = np.array(m-3*s, m+3*s,0.1)
    plt.plot(x,norm.pdf(x,m,s),'b')
    plt.title("Normal(Mean = " + str(m)+",STD = " + str(s) + ")PDF")
    plt.show()
    
def gamplt(a,b) :
    import numpy as np
    import matplotlib.pyplot as plt
    from scipy.stats import gamma
    x = np.arange(0,a*b + 6*a*b*b, 0.1)
    plt.plot(x,gamma.pdf(x,a,b), 'b')
    plt.title('Gamma(Alpha = ' + str(a) + ', Beta = ' + str(b) + ')PDF')
    plt.show()